app:
  port: 3004
  site:
      brand: BlockStamp v1
      title: BlockStamp
      slogan: Written forever.
      tagline: Instant & Secure Proof of Existence for Any Document.
      logo: "/theme/logo.svg"
      keywords:
         -blockchain
         -notary
         -proof of existence
         -bitcoin
         -p2p
         -anonymous
         -secure
         -permanent
         -distributed
         -documents
         -agreements
         -contracts
  url:
    scheme: https
    host: localhost
    port: 3004
  magicNumber: magic12345
  defaultChain: btc
  defaultNetwork: mainnet
  defaultPaymentAddress: bc1q05n5erxvcr8dfaavhgus4wnp8hpzyv0hlncygw
db:
  path: /tmp/blockstamp-database

chains:
  btc:
    networks:
      mainnet:
        incomingPrivateKey: zprvAdGr7JoJnHPmtqp7dxAxYHQBeBh3atmSNpTsbHj3ZazemcaRSu1c88fbTUiFazAMA8TdYwA87X3wxSxQrc3E8vjzkQNdQoYurA98t8Eo9x8
        outgoingPublicKey: zpub6rB1x7rJTqG1cG4MAKW9X5FhfWBobfuCfRSvbjzAcSPwNyheRhK6B8GYQhQ8GY6Tn8gbnQWNRosz2dX8bRoK1KbVwXPrjFHGHeyvYiSfaqS
        documentPrice: 100
        feeMultiplier: 2
      testnet:
        incomingPrivateKey: zprvAfUp27PhmZoZyYguZGfgpjhFZHTQQYmjRKKvBzqLSgRnyQcrrJJUZsE3cehdzzknqP9M7gEmxGDSpRQGLyAvuLXmDqkAmeKaRmKJqJRNGhm
        outgoingPublicKey: zpub6sFiEToSPiJN9e2aiNBiNE4ERjQuR62LntBNP3yUNXEKqTxKP3Nbib4rGw52rqVDHww7PSJqzvEXvvpXckdHr4BxukCNp17JfCnhBVWffVg
        documentPrice: 100
        feeMultiplier: 2

social:
  twitter: blockstamp
  telegram: EEP3LAyL8WvklWGsQ29F4g
  github: blockstamp1
  
services:
  insight:
    btc:
      mainnet:
         url: https://bitpay.com/insight/BTC/mainnet/
         api: /api
      testnet:
         url: https://test-insight.bitpay.com
         api: /api
    bch:
      mainnet:
         url:
         api: /api
      testnet:
         url:
         api: /api
mail:
  from: blockstamp@proton.com
  to: blockstamp@proton.com

nodemailer:
  options:
    jsonTransport: true
